# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83019998bfc9e2f64722576aad0cf43aa0341e52b8d76f93aae61819dd5f889d77801673489f0c61b8a39234413001c56240af059845c6140edaa85447e9551d

test:
  secret_key_base: 1c2d2686abf548564603e081dc13b3473fa68fb8b63694e17225235989dfd451b5a174734c608a9f1787d5d9b1e48eb35b27aa518335cb9943daca8933884aad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
